### ISSUE TITLE
Problematic genomic regions for custom species

### ISSUE THREAD

**Issue by Rafaelsoler13** [dozmorovlab/excluderanges#2]
Hello,

Would it be possible to create a file of problematic genomic regions for other species? (For example Chicken) It would be ideal to add a workflow to create this type of files but in other species.

Many thanks for your work :)

Best,

Rafael

**Comment by mdozmorov** [comment]
@Rafaelsoler13, creating new excludable ranges is a separate story. excluderanges is just a data package, we'll include problematic regions for other organisms and technologies as they become available. Suggestions welcome!

This tool https://github.com/Boyle-Lab/Blacklist can generate problematic regions for other organisms. The main problem is the sufficient amount of input ChIP-seq data.

**Comment by Rafaelsoler13** [comment]
Thanks!
